sudo: required
services:
  - docker

before_install:
  - docker build -t aashish-ghogre/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aashish-ghogre/react-test npm test -- --coverage

after_success:
  - docker build -t aashishghogre/multi-client ./client
  - docker build -t aashishghogre/multi-nginx ./nginx
  - docker build -t aashishghogre/multi-server ./server
  - docker build -t aashishghogre/multi-worker ./worker
  #Log in to the docker CLI
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  #Take built images and push them to docker hub
  - docker push aashishghogre/multi-client
  - docker push aashishghogre/multi-nginx
  - docker push aashishghogre/multi-server
  - docker push aashishghogre/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-292985663370"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET"
